from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 440)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(0, 120, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn7.setFont(font)
        self.btn7.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn7.setObjectName("btn7")
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(80, 120, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn8.setFont(font)
        self.btn8.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn8.setObjectName("btn8")
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(160, 120, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn9.setFont(font)
        self.btn9.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn9.setObjectName("btn9")
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(0, 200, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn4.setFont(font)
        self.btn4.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(80, 200, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn5.setFont(font)
        self.btn5.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(160, 200, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn6.setFont(font)
        self.btn6.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn6.setObjectName("btn6")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(0, 280, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn1.setFont(font)
        self.btn1.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(80, 280, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn2.setFont(font)
        self.btn2.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(160, 280, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn3.setFont(font)
        self.btn3.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn3.setObjectName("btn3")
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(0, 360, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        self.btn0.setFont(font)
        self.btn0.setStyleSheet("background-color: rgb(255, 194, 209);")
        self.btn0.setObjectName("btn0")
        self.btn_eq = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eq.setGeometry(QtCore.QRect(80, 360, 160, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_eq.setFont(font)
        self.btn_eq.setStyleSheet("background-color: rgb(251, 111, 146);")
        self.btn_eq.setObjectName("btn_eq")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(240, 360, 60, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_div.setFont(font)
        self.btn_div.setStyleSheet("background-color: rgb(255, 143, 171);")
        self.btn_div.setObjectName("btn_div")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(240, 120, 60, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("background-color: rgb(255, 143, 171);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_min = QtWidgets.QPushButton(self.centralwidget)
        self.btn_min.setGeometry(QtCore.QRect(240, 200, 60, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_min.setFont(font)
        self.btn_min.setStyleSheet("background-color: rgb(255, 143, 171);")
        self.btn_min.setObjectName("btn_min")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(240, 280, 60, 80))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_mult.setFont(font)
        self.btn_mult.setStyleSheet("background-color: rgb(255, 143, 171);")
        self.btn_mult.setObjectName("btn_mult")
        self.label_res = QtWidgets.QLabel(self.centralwidget)
        self.label_res.setGeometry(QtCore.QRect(0, 0, 300, 120))
        font = QtGui.QFont()
        font.setFamily("Uni Sans Thin Caps Italic")
        font.setPointSize(35)
        self.label_res.setFont(font)
        self.label_res.setStyleSheet("background-color: rgb(255, 229, 236);")
        self.label_res.setObjectName("label_res")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def add_functions(self):
        self.btn0.clicked.connect(lambda: self.write_number(self.btn0.text()))
        self.btn1.clicked.connect(lambda: self.write_number(self.btn1.text()))
        self.btn2.clicked.connect(lambda: self.write_number(self.btn2.text()))
        self.btn3.clicked.connect(lambda: self.write_number(self.btn3.text()))
        self.btn4.clicked.connect(lambda: self.write_number(self.btn4.text()))
        self.btn5.clicked.connect(lambda: self.write_number(self.btn5.text()))
        self.btn6.clicked.connect(lambda: self.write_number(self.btn6.text()))
        self.btn7.clicked.connect(lambda: self.write_number(self.btn7.text()))
        self.btn8.clicked.connect(lambda: self.write_number(self.btn8.text()))
        self.btn9.clicked.connect(lambda: self.write_number(self.btn9.text()))

        self.btn_plus.clicked.connect(lambda: self.write_number(self.btn_plus.text()))
        self.btn_min.clicked.connect(lambda: self.write_number(self.btn_min.text()))
        self.btn_div.clicked.connect(lambda: self.write_number(self.btn_div.text()))
        self.btn_mult.clicked.connect(lambda: self.write_number(self.btn_mult.text()))

        self.btn_eq.clicked.connect(self.calculate)

    def calculate(self):
        res = eval(self.label_res.text())
        self.label_res.setText(str(res))

    def write_number(self,number):
        if self.label_res.text() == "0":
            self.label_res.setText(str(number))
        else:
            self.label_res.setText(self.label_res.text() + str(number))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn7.setText(_translate("MainWindow", "7"))
        self.btn8.setText(_translate("MainWindow", "8"))
        self.btn9.setText(_translate("MainWindow", "9"))
        self.btn4.setText(_translate("MainWindow", "4"))
        self.btn5.setText(_translate("MainWindow", "5"))
        self.btn6.setText(_translate("MainWindow", "6"))
        self.btn1.setText(_translate("MainWindow", "1"))
        self.btn2.setText(_translate("MainWindow", "2"))
        self.btn3.setText(_translate("MainWindow", "3"))
        self.btn0.setText(_translate("MainWindow", "0"))
        self.btn_eq.setText(_translate("MainWindow", "="))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_min.setText(_translate("MainWindow", "-"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.label_res.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
